[package]
name = "encore"
version = "0.1.0"
authors = ["Michał Czyż <mike@c2yz.com>", "Bartłomiej Szkodny"]
edition = "2024"

[dependencies]
bootloader_api = "0.11.10"
com_logger = "0.1.2"
log = "0.4.26"
x86_64 = "0.15.2"
noto-sans-mono-bitmap = "0.3.1"
